---

- hosts: localhost
  connection: local
  gather_facts: no
  vars:
    - ruby_version: 2.2.6
  tasks:
    - name: install homebrew tap
      homebrew_tap: name={{ item }} state=present
      with_items: 
        - homebrew/binary
        - homebrew/dupes
        - caskroom/versions

    - name: homebrew_tap caskroom/cask
      homebrew_tap: name=caskroom/cask

    - name: homebrew_cask install item
      homebrew_cask: name={{ item }}
      with_items:
        - java7
        - google-chrome
        - virtualbox
        - vagrant
        - slack
        - skype
        - thunderbird
        - firefox
        - vlc

    - homebrew: name={{ item.name }} state={{ item.state|default("latest") }} install_options={{ item.install_options|default() }}
      with_items:
        - { name: zsh }
        - { name: lua }
        - { name: vim, install_options: with-lua }
        - { name: wget }
        - { name: tmux }
        - { name: sbt }
        - { name: doxygen }
        - { name: tree }

    - name: copy gitconfig
      copy: src=gitconfig dest=~/.gitconfig

    - name: copy zshrc
      copy: src=zshrc dest=~/.zshrc

    - name: git clone git@github.com:rbenv/rbenv.git ~/rbenv
      git: repo=https://github.com/rbenv/rbenv.git dest=~/.rbenv accept_hostkey=yes

    - name: git clone git@github.com:rbenv/ruby-build.git ~/.rbenv/plugins/ruby-build
      git: repo=https://github.com/rbenv/ruby-build.git dest=~/.rbenv/plugins/ruby-build accept_hostkey=yes

    - name: ruby install {{ ruby_version }}
      shell: export PATH="$HOME/.rbenv/bin:$PATH" && eval "$(rbenv init -)" && rbenv install {{ ruby_version }} && rbenv global {{ ruby_version }} && rbenv rehash creates=~/.rbenv/versions/{{ ruby_version }}

    - name: gem install bundler
      gem: name=bundler user_install=False
      become: true
