---

- hosts: localhost
  connection: local
  gather_facts: no
  tasks:
    - name: install homebrew tap
      homebrew_tap: name={{ item }} state=present
      with_items: 
        - homebrew/binary
        - homebrew/dupes
        - caskroom/versions

    - name: homebrew_tap caskroom/cask
      homebrew_tap: name=caskroom/cask

    - name: homebrew_cask install item
      homebrew_cask: name={{ item }}
      with_items:
        - java7
        - google-chrome
        - virtualbox
        - vagrant
        - slack
        - skype
        - thunderbird
        - firefox
        - vlc

    - homebrew: name={{ item.name }} state={{ item.state|default("latest") }} install_options={{ item.install_options|default() }}
      with_items:
        - { name: zsh }
        - { name: lua }
        - { name: vim, install_options: with-lua }
        - { name: wget }
        - { name: tmux }
        - { name: sbt }
        - { name: doxygen }
        - { name: rbenv }
        - { name: rbenv-gemset }

    - name: copy gitconfig
      copy: src=gitconfig dest=~/.gitconfig

    - name: gem install bundler
      gem: name=bundler user_install=False
      become: true
