---

- hosts: localhost
  connection: local
  gather_facts: no
  tasks:
    - name: install brew
      homebrew:
        name:
          - wget
          - tmux
          - sbt
          - jq
          - tree
          - htop
          - awscli
          - jq
          - gnu-sed

    - name: copy gitconfig
      copy:
        src: gitconfig
        dest: ~/.gitconfig

    - name: copy zshrc
      copy:
        src: zshrc
        dest: ~/.zshrc
