---

- hosts: localhost
  connection: local
  gather_facts: no

  vars:
    homebrew_packages_taps:
      - homebrew/binary
      - homebrew/dupes
      - caskroom/versions
    homebrew_packages_packages:
      - { name: zsh }
      - { name: lua }
      - { name: vim, install_options: with-lua }
      - { name: wget }
      - { name: tmux }
      - { name: scala }
      - { name: sbt }
    homebrew_cask_packages_packages:
      - java7
      - java8
      - google-chrome
      - virtualbox
      - vagrant

  tasks:
    - homebrew_tap: tap={{ item }} state=present
      with_items: homebrew_packages_taps
    - homebrew: update_homebrew=yes
    - homebrew: name={{ item.name }} state={{ item.state|default("latest") }} install_options={{ item.install_options|default() }}
      with_items: homebrew_packages_packages

    - homebrew_tap: tap=caskroom/cask state=present
    - homebrew: name=brew-cask state=latest
    - homebrew_cask: name={{ item }} state=installed
      with_items: homebrew_cask_packages_packages
