---

- hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: install brew
      homebrew:
        name:
          - wget
          - tmux
          - sbt
          - jq
          - tree
          - htop
          - awscli
          - jq
          - gnu-sed

    - name: git clone https://github.com/VundleVim/Vundle.vim.git
      git:
        repo: https://github.com/VundleVim/Vundle.vim.git
        version: master
        dest: ~/.vim/bundle/Vundle.vim
        accept_hostkey: true

    - name: copy vimrc
      copy:
        src: vimrc
        dest: ~/.vimrc
      register: vimrc

    - name: vim +PluginInstall +qall
      command: vim +PluginInstall +qall
      when: vimrc is changed

    - name: copy gitconfig
      copy:
        src: gitconfig
        dest: ~/.gitconfig

    - name: copy zshrc
      copy:
        src: zshrc
        dest: ~/.zshrc
