---

- hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: install brew
      homebrew:
        name:
          - wget
          - tmux
          - sbt
          - jq
          - tree
          - htop
          - awscli
          - jq
          - gnu-sed
          - shellcheck
          - zsh-autosuggestions
          - zsh-syntax-highlighting
          - peco
          - imagemagick
          - watch
          - node

    - name: brew tap AdoptOpenJDK/openjdk
      homebrew_tap:
        name: AdoptOpenJDK/openjdk

    - name: brew cask install adoptopenjdk/openjdk/adoptopenjdk11
      homebrew_cask:
        name: adoptopenjdk/openjdk/adoptopenjdk11

    - name: git clone https://github.com/VundleVim/Vundle.vim.git
      git:
        repo: https://github.com/VundleVim/Vundle.vim.git
        version: master
        dest: ~/.vim/bundle/Vundle.vim
        accept_hostkey: true

    - name: copy vimrc
      copy:
        src: vimrc
        dest: ~/.vimrc
      register: vimrc

    - name: vim +PluginInstall +qall
      command: vim +PluginInstall +qall
      when: vimrc is changed

    - name: copy gitconfig
      copy:
        src: gitconfig
        dest: ~/.gitconfig

    - name: copy zshrc
      copy:
        src: zshrc
        dest: ~/.zshrc
