version: 2.1
jobs:
  build:
    docker:
      - image: cimg/python:3.8.13
    steps:
      - checkout
      - run: python --version
      - run: sudo apt-get install libyaml-dev
      - run: sudo pip install ansible
      - run: ansible --version
      - run: ansible-playbook -i hosts localhost.yml --syntax-check
