version: 2.1
jobs:
  build:
    docker:
      - image: cimg/python:3.8.13
    steps:
      - checkout
      - run: python --version
      - run: pip3 install ansible ansible-lint
      - run: ansible --version
      - run: ansible-playbook -i hosts localhost.yml --syntax-check
      - run: ansible-lint localhost.yml
